swagger:
  api:
    enabled: true
    title: The Link Thing
    description: this service provides the apis for the link thing operations
    version: 1.0.0
  docs:
    contact:
      name: Onkar Raut

spring:
  datasource:
    url: jdbc:h2:mem:thelinkthing
    driver-class-name: org.h2.Driver
    username: username
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      format-sql: true
    hibernate:
      use-new-id-generator-mappings: false
  h2:
    console:
      enabled: true

server:
  servlet:
    context-path: /tlt/api


security:
  auth:
    enabled: true
    key: 5OChHUNmaTmK4L4OJQBqJml3t0